* Encoding: UTF-8.

DATASET ACTIVATE DataSet1.
FREQUENCIES VARIABLES=Age Sex Education Ethnicity UnitsDay DaysWeek_Alc BingeOccassions 
    ConditionOrder
  /STATISTICS=STDDEV RANGE MINIMUM MAXIMUM MEAN MODE
  /ORDER=ANALYSIS.
OUTPUT MODIFY
  /SELECT TABLES
  /IF COMMANDS=["Frequencies(LAST)"] SUBTYPES="Frequencies"
  /TABLECELLS SELECT=[VALIDPERCENT CUMULATIVEPERCENT] APPLYTO=COLUMN HIDE=YES
  /TABLECELLS SELECT=[TOTAL] SELECTCONDITION=PARENT(VALID MISSING) APPLYTO=ROW HIDE=YES
  /TABLECELLS SELECT=[VALID] APPLYTO=ROWHEADER UNGROUP=YES
  /TABLECELLS SELECT=[PERCENT] SELECTDIMENSION=COLUMNS FORMAT="PCT" APPLYTO=COLUMN
  /TABLECELLS SELECT=[COUNT] APPLYTO=COLUMNHEADER REPLACE="N"
  /TABLECELLS SELECT=[PERCENT] APPLYTO=COLUMNHEADER REPLACE="%".

DESCRIPTIVES VARIABLES=AUDIT DaysWeek_Alc UnitsDay BingeOccassions H_Units H_eBAC H_Time 
    H_MeanmAHSS H_OneItem_Hangover
  /STATISTICS=MEAN STDDEV RANGE MIN MAX.

EXAMINE VARIABLES=NH_AvgPumps H_AvgPumps
  /PLOT BOXPLOT STEMLEAF HISTOGRAM NPPLOT
  /COMPARE GROUPS
  /STATISTICS DESCRIPTIVES
  /CINTERVAL 95
  /MISSING LISTWISE
  /NOTOTAL.

GLM NH_AvgPumps H_AvgPumps WITH BIS11
  /WSFACTOR=Hangover 2 Polynomial 
  /METHOD=SSTYPE(3)
  /SAVE=PRED RESID ZRESID COOK
  /PLOT=PROFILE(Hangover) TYPE=BAR ERRORBAR=SE(2) MEANREFERENCE=NO
  /EMMEANS=TABLES(Hangover) WITH(BIS11=MEAN)COMPARE ADJ(BONFERRONI)
  /PRINT=DESCRIPTIVE ETASQ HOMOGENEITY 
  /CRITERIA=ALPHA(.05)
  /WSDESIGN=Hangover 
  /DESIGN=BIS11.

T-TEST PAIRS=NH_AvgPumps NH_RSME WITH H_AvgPumps H_RSME (PAIRED)
  /ES DISPLAY(TRUE) STANDARDIZER(SD)
  /CRITERIA=CI(.9500)
  /MISSING=ANALYSIS.
